### ISSUE TITLE
access redis from helloworld nodejs openfaas function

### ISSUE THREAD

**Issue by xpoveda** [openfaas/serverless-openfaas-nodejs#1]
Hi, I try to add to the function the access to redis but not work.

 The documentation about openfaas is simply fantastic but with redis I don't found no complete example (yes with mongodb).

I work with docker swarm and I have installed redis service with the stack miredis in the network func_functions. I have tested redis-cli and works ok.
```
root@ubuntu:~/serverless-openfaas-nodejs# cat redis.yml
version: "3"
services:

  redis:
    image: redis:alpine
    networks:
      - func_functions
    deploy:
      replicas: 1

networks:
  func_functions:
    external: true
```
```
root@ubuntu:~/serverless-openfaas-nodejs# docker stack deploy --compose-file redis.yml miredis
Creating service miredis_redis

root@ubuntu:~/serverless-openfaas-nodejs# docker run -it --network func_functions --rm redis redis-cli -h miredis_redis
miredis_redis:6379> set nombre xavi
OK
miredis_redis:6379> get nombre
"xavi"
```
I have this services
```
root@ubuntu:~/serverless-openfaas-nodejs/hello-world# docker service ls
ID                  NAME                MODE                REPLICAS            IMAGE                         PORTS
ipjbu7jge7aj        func_alertmanager   replicated          1/1                 prom/alertmanager:v0.16.1
o07j4uyancc1        func_faas-swarm     replicated          1/1                 openfaas/faas-swarm:0.6.1
7sqew5xbv59l        func_gateway        replicated          1/1                 openfaas/gateway:0.11.1       *:8080->8080/tcp
nkaeqzgvcbzf        func_nats           replicated          1/1                 nats-streaming:0.11.2
lv920tv1dakb        func_prometheus     replicated          1/1                 prom/prometheus:v2.7.1        *:9090->9090/tcp
vy9b39884x2g        func_queue-worker   replicated          1/1                 openfaas/queue-worker:0.7.1
r6xnk3ee3op8        miredis_redis       replicated          1/1                 redis:alpine
```

I have modified these files
```
root@ubuntu:~/serverless-openfaas-nodejs/template/node# grep redis Dockerfile
RUN npm install redis
```

```
root@ubuntu:~/serverless-openfaas-nodejs# cat serverless.yml
provider:
  name: faas
  gateway: http://127.0.0.1:8080
  network: func_functions

functions:
  hello-world:
    lang: node
    handler: ./hello-world
    image: xpoveda/hello-world:0.1
    environment:
      redis: miredis_redis
```

```
root@ubuntu:~/serverless-openfaas-nodejs/hello-world# cat handler.js
"use strict"

module.exports = (context, callback) => {

    var redis  = require("redis");
    var client = redis.createClient(6379, process.env.redis);

    client.on("error", function (err) {
       console.log("Error " + err);
    });

    callback(undefined, {status: "done"});
}
```
I deploy the function
```
root@ubuntu:~/serverless-openfaas-nodejs# faas build -f serverless.yml; faas push -f serverless.yml; faas deploy -f serverless.yml
....
```
```
root@ubuntu:~/serverless-openfaas-nodejs# docker service ls | grep hello
x58jh99xnhk9        hello-world         replicated          1/1                 xpoveda/hello-world:0.1
```

But when I execute the curl wait all time without response and I must to do a "control-c".
```
root@ubuntu:~/serverless-openfaas-nodejs# curl http://127.0.0.1:8080/function/hello-world
^C
```

Can you help me please?.

Thanks so much in advance.

Xavier.

**Comment by xpoveda** [comment]
Solved with the help of...

https://gist.github.com/alexellis/e05a7b573ae22b209f0214d5766ff07e

I have modified package.json adding the redis dependency and all ok.

thanks so much!!

```
root@ubuntu:~/serverless-openfaas-nodejs# cat serverless.yml
provider:
  name: faas
  gateway: http://127.0.0.1:8080
  network: func_functions

functions:
  hello-world:
    lang: node
    handler: ./hello-world
    image: xpoveda/hello-world:0.1
    environment:
      redis_host: miredis_redis
      redis_port: 6379
      write: debug
```

```
root@ubuntu:~/serverless-openfaas-nodejs/hello-world# cat handler.js
"use strict"
const redis = require("redis");

module.exports = (body, callback) => {

    const client = redis.createClient(process.env.redis_port, process.env.redis_host);

    client.on("error", function (err) {
        console.log("Error " + err);
    });

    client.set("string key", "string val", redis.print);
    client.hset("hash key",  "hashtest 1", "some value", redis.print);
    client.hset(["hash key", "hashtest 2", "some other value"], redis.print);

    client.hkeys("hash key", function (err, replies) {
        console.log(replies.length + " replies:");
        replies.forEach(function (reply, i) {
            console.log(" " + i + ": " + reply);
        });
    });

    client.set('mytime', new Date().toString());
    client.quit();

    callback(null, { status: 'xavi set done' });
}
```
```
root@ubuntu:~/serverless-openfaas-nodejs/hello-world# cat package.json
{
  "name": "function",
  "version": "1.0.0",
  "description": "",
  "main": "handler.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "redis": "^2.8.0"
  }
}
```

```
root@ubuntu:~/serverless-openfaas-nodejs/hello-world# curl http://127.0.0.1:8080/function/hello-world
{"status":"xavi set done"}
Reply: OK
Reply: 0
Reply: 0
2 replies:
 0: hashtest 1
 1: hashtest 2
```

```
miredis_redis:6379> get "mytime"
"Sat Mar 16 2019 01:39:22 GMT+0000 (UTC)"
miredis_redis:6379> get "string key"
"string val"
miredis_redis:6379> hget "hash key" "hashtest 1"
"some value"
miredis_redis:6379> hget "hash key" "hashtest 2"
"some other value"
```
